"""Case cycle through the service layer: open → audit → findings → pack → seal → rerun → review.
Behaviour contracts only (no snapshot counts of generated bytes)."""
import json
import shutil
from pathlib import Path

import pytest

from plugins.ghost_recon.core import casefolder as cf, review, service, swarm
from plugins.ghost_recon.core.reports import pack


def _initial(store, demo_case):
    s = service.open_case(store, str(demo_case), name="Demo")
    a = service.start_audit(store, s["case"]["id"], "initial")
    return s["case"]["id"], a


def test_open_case_is_idempotent_and_reimports_from_mirror(store, demo_case):
    s1 = service.open_case(store, str(demo_case))
    s2 = service.open_case(store, str(demo_case))
    assert s1["case"]["id"] == s2["case"]["id"] and s2["created"] is False
    # simulate a lost DB: a fresh store re-imports from case.json
    from plugins.ghost_recon.core.db import Store, connect
    fresh = Store(connect(":memory:"))
    s3 = service.open_case(fresh, str(demo_case))
    assert s3["case"]["id"] == s1["case"]["id"]


def test_start_audit_refuses_second_initial_and_requires_seal_before_rerun(store, demo_case):
    cid, a = _initial(store, demo_case)
    with pytest.raises(service.CaseError):
        service.start_audit(store, cid, "initial")
    with pytest.raises(service.CaseError):  # A01 still open
        service.start_audit(store, cid, "rerun")


def test_seal_requires_completion_unless_forced(store, demo_case):
    cid, a = _initial(store, demo_case)
    res = service.seal_audit(store, a["audit"]["id"])
    assert res["sealed"] is False and "report_md" in res["completion"]["missing"]
    forced = service.seal_audit(store, a["audit"]["id"], force=True)
    assert forced["sealed"] and forced["forced"] is True


def test_full_cycle_rerun_dedupe_and_review(store, demo_case):
    cid, a = _initial(store, demo_case)
    aid = a["audit"]["id"]; folder = Path(a["folder"])
    plan = swarm.plan_extraction(store, aid)
    assert plan["tasks"] and all("skill_view(name='ghost-recon-block-auditor')" in t["goal"] for t in plan["tasks"])
    assert all(set(t) == {"goal", "context", "output_schema", "group"} for t in swarm.strip_for_delegate(plan["tasks"]))
    service.upsert_findings(store, aid, [{"kind": "exception", "title": "x", "amount": 1, "risk": "high"}])
    cf.write_json(folder, "03_Extracted_Data/model.json", {"kpis": {"a": 1}})
    cf.write_text(folder, "06_Report/report.md", "## 1. Respuesta\n\nTexto.\n")
    res = pack.build_pack(store, aid)
    assert {f["format"] for f in res["files"]} == {"md", "pdf", "xlsx"} and not res["warnings"]
    service.record_run(store, aid, "validation", role="A", status="done", summary="ok")
    assert service.seal_audit(store, aid)["sealed"]
    # rerun with one new file and one duplicate copy
    (demo_case / "Bancos" / "nuevo.txt").write_text("nuevo", encoding="utf-8")
    shutil.copy(demo_case / "Facturas" / "FAC-2026-001.csv", demo_case / "Facturas" / "copia.csv")
    b = service.start_audit(store, cid, "rerun")
    ev = b["evidence"]
    assert ev["NEW"] == 1 and ev["DUP_PRIOR"] == 1 and ev["REGISTERED"] == 9
    assert [f["id"] for f in b["inherited_open_findings"]] == ["EXC-01"]
    assert (Path(b["folder"]) / "Evidence_Pass" / "dedupe.json").exists()
    assert service.verify_audit(store, aid)["ok"]
    # modified evidence is flagged
    bid = b["audit"]["id"]
    service.record_run(store, bid, "validation", role="B", status="done", summary="ok")
    cf.write_text(Path(b["folder"]), "06_Report/report.md", "## 00\n\nx\n")
    cf.write_json(Path(b["folder"]), "03_Extracted_Data/model.json", {"kpis": {}})
    pack.build_pack(store, bid)
    assert service.seal_audit(store, bid)["sealed"]
    (demo_case / "Bancos" / "nuevo.txt").write_text("cambiado", encoding="utf-8")
    c = service.start_audit(store, cid, "rerun")
    assert "Bancos/nuevo.txt" in c["audit"]["summary"]["modified_evidence"]
    service.seal_audit(store, c["audit"]["id"], force=True)
    # review
    rv = review.start_review(store, cid)
    assert len(rv["plan"]["tasks"]) == 6 and {t["role"] for t in rv["plan"]["tasks"]} == {r["key"] for r in review.ROLES}
    chron = (Path(rv["folder"]) / "chronology.md").read_text(encoding="utf-8")
    assert "EXC-01" in chron and "A01" in chron and "A02" in chron
    status = service.case_status(store, cid)
    assert [x["kind"] for x in status["audits"]] == ["initial", "rerun", "rerun", "review"]


def test_timeline_tracks_events(store, demo_case):
    cid, a = _initial(store, demo_case)
    t = service.timeline(store, cid)
    assert [e["event_type"] for e in t["events"]][:2] == ["case_opened", "audit_started"]


def test_evidence_index_filters(store, demo_case):
    cid, a = _initial(store, demo_case)
    idx = service.evidence_index(store, a["audit"]["id"], block="banking")
    assert idx["count"] >= 2 and all(r["block"] == "banking" for r in idx["rows"])


def test_open_case_between_seal_and_rerun_keeps_audited_hashes(store, demo_case):
    """The skills call gr_case_open before gr_audit_start(rerun): that must not turn new files into DUP_PRIOR
    nor hide a tampered audited file (regression for the review finding)."""
    cid, a = _initial(store, demo_case)
    aid = a["audit"]["id"]
    service.seal_audit(store, aid, force=True)
    (demo_case / "Bancos" / "nuevo.txt").write_text("nuevo", encoding="utf-8")
    (demo_case / "Facturas" / "FAC-2026-002.csv").write_text("tampered", encoding="utf-8")
    service.open_case(store, str(demo_case))          # the step the orchestrator skills perform first
    b = service.start_audit(store, cid, "rerun")
    ev = b["evidence"]
    assert ev["NEW"] == 1 and ev.get("MODIFIED") == 1 and ev.get("DUP_PRIOR", 0) == 0
    assert b["audit"]["summary"]["modified_evidence"] == ["Facturas/FAC-2026-002.csv"]
    plan = swarm.plan_extraction(store, b["audit"]["id"])
    assert sorted(f["rel"] for t in plan["tasks"] for f in json.loads(Path(t["manifest"]).read_text(encoding="utf-8"))["files"]) == \
        ["Bancos/nuevo.txt", "Facturas/FAC-2026-002.csv"]
    row = next(e for e in store.list_evidence(cid) if e["path"] == "Facturas/FAC-2026-002.csv")
    assert row["meta"]["previous_hashes"][0]["audit_id"] == aid


def test_unreadable_zip_member_does_not_abort_intake(store, demo_case):
    import zipfile
    # a member flagged as encrypted: zipfile raises RuntimeError on open (no password)
    z = demo_case / "Bancos" / "cifrado.zip"
    with zipfile.ZipFile(z, "w") as zf:
        zf.writestr("secreto.csv", "a,b")
    data = bytearray(z.read_bytes())
    # set the encryption bit (bit 0 of general purpose flags) in the local header and central directory
    for sig in (b"PK\x03\x04", b"PK\x01\x02"):
        i = data.find(sig)
        off = 6 if sig == b"PK\x03\x04" else 8
        data[i + off] |= 1
    z.write_bytes(bytes(data))
    s = service.open_case(store, str(demo_case))
    rows = {e["path"]: e for e in store.list_evidence(s["case"]["id"])}
    assert rows["Bancos/cifrado.zip::secreto.csv"]["status"] == "UNREADABLE"
    a = service.start_audit(store, s["case"]["id"], "initial")
    assert a["evidence"].get("UNREADABLE") == 1
